basePath: /
host: localhost:1323
info:
  contact:
    email: muhammaddaffadinaya@gmail.com
    name: Apipodlabs
    url: https://github.com/apipodlabs/oxign/issues
  description: Restful API Documentation on Oxign Platform.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Oxign API Documentation
  version: 0.0.1
paths:
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
schemes:
- http
swagger: "2.0"
